package civ.cnam.enrolment.domain.model.value

enum class EnrolmentActionKind {
    PHOTO_ATTACHED,
    FINGERPRINTS_ATTACHED,
    IDENTITY_DOCUMENT_ATTACHED,
    SUPPORTING_DOCUMENT_ATTACHED,
    SIGNATURE_ATTACHED,
    ENROLMENT_DETAILS_UPDATED,
    ENROLMENT_DEDUPE_MATCHED,
    ENROLMENT_COMPLETED,
    ENROLMENT_APPROVED,
    ENROLMENT_PROCESSED,
}