kind: ConfigMap
apiVersion: v1
metadata:
  name: scheduled-job-config
  namespace: mobis
data:
  alert_outbox_job_enabled: "true"
  verification_outbox_job_enabled: "true"
  enrolment_outbox_job_enabled: "true"
