apiVersion: v1
kind: Service
metadata:
  name: cnam-api-nodeport
  namespace: mobis
  labels:
    app.kubernetes.io/name: cnam-api
    app.kubernetes.io/version: <version>
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9191
      nodePort: 31080
  selector:
    app.kubernetes.io/name: cnam-api
  type: NodePort